#ifndef TRANSPARENT_PART_GLOBAL_H
#define TRANSPARENT_PART_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRANSPARENT_PART_LIBRARY)
#  define TRANSPARENT_PARTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRANSPARENT_PARTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSPARENT_PART_GLOBAL_H
